# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: ke2ek
name: Eunjin Kwon
email: gej48443@gmail.com
footer_text: >
  <a href="https://github.com/ke2ek">Github</a>
  <a href="./">LinkedIn</a>
url: https://ke2ek.github.io # the base hostname & protocol for your site

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: ke2ek

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: /blog/tags/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: ke2ek # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
rouge: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll-tagging
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
